import { supabase } from '../integrations/supabase/client';
import { monthStart,today } from '../lib/format';
import type { DashboardData,FinancialTransaction } from '../types';
export async function getTransactions(type?:'income'|'expense'){let q=supabase.from('financial_transactions').select('*,professional:professionals(name),category:financial_categories(name)').is('deleted_at',null).order('competence_date',{ascending:false}).limit(100);if(type)q=q.eq('transaction_type',type);const{data,error}=await q;if(error)throw error;return data as FinancialTransaction[]}
export async function saveTransaction(input:Record<string,unknown>){const{data,error}=await supabase.from('financial_transactions').insert(input).select().single();if(error)throw error;return data}
export async function updateTransaction(id:string,input:Record<string,unknown>){const{error}=await supabase.from('financial_transactions').update(input).eq('id',id);if(error)throw error}
export async function cancelTransaction(id:string){return updateTransaction(id,{status:'cancelled',deleted_at:new Date().toISOString()})}
export async function getDashboard():Promise<DashboardData>{const start=monthStart(),now=today();const{data,error}=await supabase.from('financial_transactions').select('transaction_type,net_amount,status,competence_date,due_date').gte('competence_date',start).neq('status','cancelled').is('deleted_at',null);if(error)throw error;const rows=data||[];const sum=(t:string,p:(r:any)=>boolean)=>rows.filter(r=>r.transaction_type===t&&p(r)).reduce((a,r)=>a+Number(r.net_amount),0);const dayIncome=sum('income',r=>r.competence_date===now&&r.status==='received'),monthIncome=sum('income',r=>r.status==='received'),dayExpense=sum('expense',r=>r.competence_date===now&&r.status==='paid'),monthExpense=sum('expense',r=>r.status==='paid');const chart=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const key=d.toISOString().slice(0,10);return{label:d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),receitas:sum('income',r=>r.competence_date===key),despesas:sum('expense',r=>r.competence_date===key)}});const[{data:cash},{data:commissions}]=await Promise.all([supabase.from('cash_registers').select('initial_balance,expected_balance').eq('status','open').maybeSingle(),supabase.from('commissions').select('commission_amount').eq('status','pending')]);return{dayIncome,monthIncome,dayExpense,monthExpense,profit:monthIncome-monthExpense,receivable:sum('income',r=>['pending','partial','overdue'].includes(r.status)),payable:sum('expense',r=>['pending','partial','overdue'].includes(r.status)),cashBalance:Number(cash?.expected_balance??cash?.initial_balance??0),pendingCommissions:(commissions||[]).reduce((a,r)=>a+Number(r.commission_amount),0),movementCount:rows.filter(r=>r.competence_date===now).length,chart}}



