import { useEffect, useState, type ReactNode } from 'react';
import { ArrowLeft, Bell, CalendarDays, Clock, Phone, Scissors, UserRound, X } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '../integrations/supabase/client';

type Notification = { id:string; starts_at:string; status:string; created_at?:string; customer?:{name:string;phone?:string|null}|null; service?:{name:string}|null };
const labels:Record<string,string>={scheduled:'Aguardando confirmação',confirmed:'Confirmado',completed:'Concluído',cancelled:'Cancelado'};

export function AppointmentNotifier(){
 const[items,setItems]=useState<Notification[]>([]),[count,setCount]=useState(0),[open,setOpen]=useState(false),[selected,setSelected]=useState<Notification|null>(null);
 async function load(){const{data}=await supabase.from('appointments').select('id,starts_at,status,created_at,customer:customers(name,phone),service:services(name)').order('created_at',{ascending:false}).limit(10);setItems((data||[])as unknown as Notification[])}
 useEffect(()=>{void load();const channel=supabase.channel('new-appointments').on('postgres_changes',{event:'*',schema:'public',table:'appointments'},payload=>{setCount(v=>v+1);void load();toast.success(payload.eventType==='UPDATE'?'Agendamento atualizado!':'Novo agendamento recebido!',{description:'Clique no sino para visualizar os detalhes.'})}).subscribe();return()=>{void supabase.removeChannel(channel)}},[]);
 function toggle(){setOpen(v=>!v);setSelected(null);if(!open)setCount(0)}
 return <div className="relative ml-auto mr-3"><button onClick={toggle} title="Notificações" aria-label="Abrir notificações" className="relative grid size-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50"><Bell size={19}/>{count>0&&<span className="absolute -right-1 -top-1 grid min-w-5 place-items-center rounded-full bg-rose-500 px-1 text-[11px] font-bold text-white">{count}</span>}</button>
 {open&&<><button className="fixed inset-0 z-30 cursor-default" aria-label="Fechar notificações" onClick={()=>setOpen(false)}/><section className="fixed inset-x-3 top-[4.5rem] z-40 max-h-[calc(100vh-6rem)] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl sm:absolute sm:inset-x-auto sm:right-0 sm:top-12 sm:w-[380px]">
 {selected?<Details item={selected} back={()=>setSelected(null)} close={()=>setOpen(false)}/>:<><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold text-slate-900">Notificações</h2><p className="text-xs text-slate-500">Agendamentos recentes</p></div><button onClick={()=>setOpen(false)} className="grid size-9 place-items-center rounded-lg hover:bg-slate-100"><X size={18}/></button></div><div className="max-h-[60vh] overflow-y-auto">{!items.length?<p className="p-8 text-center text-sm text-slate-500">Nenhuma notificação por enquanto.</p>:items.map(item=><button key={item.id} onClick={()=>setSelected(item)} className="flex w-full gap-3 border-b px-5 py-4 text-left hover:bg-violet-50/60"><span className="mt-1 grid size-9 shrink-0 place-items-center rounded-full bg-violet-100 text-violet-700"><CalendarDays size={17}/></span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-slate-900">{item.customer?.name||'Cliente'}</b><span className="mt-1 block text-xs text-slate-500">{date(item.starts_at)} às {time(item.starts_at)}</span><span className="mt-1 block text-xs font-medium text-violet-600">{labels[item.status]||item.status} · Ver detalhes</span></span></button>)}</div></>}</section></>}
 </div>
}
function Details({item,back,close}:{item:Notification;back:()=>void;close:()=>void}){return <><div className="flex items-center justify-between border-b px-4 py-3"><button onClick={back} className="flex items-center gap-2 rounded-lg px-2 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100"><ArrowLeft size={18}/>Voltar</button><button onClick={close} className="grid size-9 place-items-center rounded-lg hover:bg-slate-100"><X size={18}/></button></div><div className="space-y-5 p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-violet-600">Detalhes do agendamento</p><h3 className="mt-1 text-xl font-bold">{item.customer?.name||'Cliente'}</h3><span className="mt-2 inline-flex rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{labels[item.status]||item.status}</span></div><div className="space-y-3 rounded-2xl bg-slate-50 p-4 text-sm"><Detail icon={<UserRound size={18}/>} label="Cliente" value={item.customer?.name||'Não informado'}/><Detail icon={<Phone size={18}/>} label="WhatsApp ou telefone" value={item.customer?.phone||'Não informado'}/><Detail icon={<CalendarDays size={18}/>} label="Data" value={date(item.starts_at)}/><Detail icon={<Clock size={18}/>} label="Horário" value={time(item.starts_at)}/><Detail icon={<Scissors size={18}/>} label="Procedimento" value={item.service?.name||'Será definido ao confirmar'}/></div></div></>}
function Detail({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="flex gap-3"><span className="mt-0.5 text-violet-600">{icon}</span><span><span className="block text-xs text-slate-500">{label}</span><b className="text-slate-800">{value}</b></span></div>}
function date(v:string){return new Date(v).toLocaleDateString('pt-BR')}function time(v:string){return new Date(v).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}