create table if not exists public.transaction_payments(id uuid primary key default gen_random_uuid(),transaction_id uuid not null references public.financial_transactions(id),payment_method_id uuid not null references public.payment_methods(id),amount numeric(12,2) not null check(amount>0),installments int not null default 1 check(installments>0),paid_at timestamptz not null default now());
alter table public.transaction_payments enable row level security;
drop policy if exists payments_select on public.transaction_payments;
create policy payments_select on public.transaction_payments for select to authenticated using(public.my_role() is not null);
drop policy if exists payments_insert on public.transaction_payments;
create policy payments_insert on public.transaction_payments for insert to authenticated with check(public.my_role() is not null);
alter table public.appointments add column if not exists transaction_id uuid references public.financial_transactions(id);
create unique index if not exists appointment_single_transaction on public.appointments(transaction_id) where transaction_id is not null;
insert into public.payment_methods(name,maximum_installments) values('Dinheiro',1),('PIX',1),('Cartão de débito',1),('Cartão de crédito',12) on conflict(name) do update set active=true;
insert into public.financial_categories(name,type) values('Procedimentos','income'),('Fornecedor','expense'),('Materiais e produtos','expense'),('Alimentação','expense'),('Contas','expense'),('Outras saídas','expense') on conflict(name,type) do update set active=true;
create or replace function public.update_cash_balance() returns trigger language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from cash_registers where id=new.cash_register_id and status='open') then raise exception 'O caixa está fechado';end if;update cash_registers set expected_balance=expected_balance+(case when new.type in('inflow','reinforcement','receipt') then new.amount else -new.amount end) where id=new.cash_register_id;return new;end$$;
drop trigger if exists cash_movement_balance on public.cash_movements;
create trigger cash_movement_balance after insert on public.cash_movements for each row execute function public.update_cash_balance();
create or replace function public.finish_appointment(p_appointment uuid,p_payment_method uuid,p_amount numeric default null) returns uuid language plpgsql security definer set search_path=public as $$
declare a appointments%rowtype;s services%rowtype;c uuid;tx uuid;amount numeric(12,2);begin select * into a from appointments where id=p_appointment for update;if a.id is null then raise exception 'Atendimento não encontrado';end if;if a.transaction_id is not null then return a.transaction_id;end if;select * into s from services where id=a.service_id;amount:=coalesce(p_amount,s.price);if amount<=0 then raise exception 'Informe um valor válido';end if;select id into c from cash_registers where status='open' and opened_at::date=current_date limit 1;if c is null then raise exception 'Abra o caixa de hoje antes de finalizar o atendimento';end if;insert into financial_transactions(cash_register_id,customer_id,professional_id,category_id,transaction_type,origin_type,description,gross_amount,competence_date,payment_date,status,created_by) values(c,a.customer_id,a.professional_id,s.category_id,'income','appointment','Atendimento: '||s.name,amount,current_date,current_date,'received',auth.uid()) returning id into tx;insert into transaction_payments(transaction_id,payment_method_id,amount) values(tx,p_payment_method,amount);insert into cash_movements(cash_register_id,type,description,amount,payment_method_id,transaction_id,created_by) values(c,'receipt','Atendimento: '||s.name,amount,p_payment_method,tx,auth.uid());update appointments set status='completed',transaction_id=tx where id=a.id;return tx;end$$;
create or replace function public.register_cash_expense(p_category uuid,p_description text,p_amount numeric,p_payment_method uuid default null) returns uuid language plpgsql security definer set search_path=public as $$
declare c uuid;tx uuid;begin if trim(coalesce(p_description,''))='' or p_amount<=0 then raise exception 'Preencha descrição e valor';end if;select id into c from cash_registers where status='open' and opened_at::date=current_date limit 1;if c is null then raise exception 'Abra o caixa de hoje antes de registrar uma saída';end if;insert into financial_transactions(cash_register_id,category_id,transaction_type,origin_type,description,gross_amount,competence_date,payment_date,status,created_by) values(c,p_category,'expense','cash_register',p_description,p_amount,current_date,current_date,'paid',auth.uid()) returning id into tx;insert into cash_movements(cash_register_id,type,description,amount,payment_method_id,transaction_id,created_by) values(c,'outflow',p_description,p_amount,p_payment_method,tx,auth.uid());return tx;end$$;

