import { useState } from 'react';import { NavLink,Outlet } from 'react-router-dom';import {BarChart3,CalendarDays,ChevronLeft,ChevronRight,CircleDollarSign,LayoutDashboard,LogOut,Menu,ReceiptText,Scissors,Settings,Users,WalletCards,X}from'lucide-react';import { useAuth } from '../contexts/AuthContext';import { AppointmentNotifier } from '../components/AppointmentNotifier';
const items=[['/agenda','Agenda',CalendarDays],['/','Visão geral',LayoutDashboard],['/procedimentos','Procedimentos',Scissors],['/receitas','Receitas',CircleDollarSign],['/despesas','Despesas',ReceiptText],['/caixa','Caixa',WalletCards],['/clientes','Clientes',Users],['/relatorios','Relatórios',BarChart3],['/configuracoes','Configurações',Settings]] as const;
export function AppLayout(){const[small,setSmall]=useState(false),[mobile,setMobile]=useState(false);const{profile,signOut}=useAuth();return <div className="min-h-screen bg-slate-50"><aside className={`fixed inset-y-0 left-0 z-40 flex flex-col border-r border-slate-200 bg-white transition-all ${small?'lg:w-20':'lg:w-64'} ${mobile?'w-72 translate-x-0':'w-72 -translate-x-full lg:translate-x-0'}`}><div className="flex h-20 items-center justify-between px-5"><div className="flex items-center gap-3 overflow-hidden"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-600 font-bold text-white">K</div>{!small&&<div><p className="font-bold">Kavelar Feminine Beaty</p><p className="text-xs text-slate-500">Gestão do salão</p></div>}</div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div><nav className="flex-1 space-y-1 px-3">{items.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setMobile(false)} className={({isActive})=>`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium ${isActive?'bg-violet-50 text-violet-700':'text-slate-600 hover:bg-slate-50'}`}><Icon size={20}/>{!small&&label}</NavLink>)}</nav><div className="border-t p-3"><button className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm text-slate-600 hover:bg-slate-50" onClick={signOut}><LogOut size={20}/>{!small&&'Sair'}</button></div><button aria-label="Recolher menu" onClick={()=>setSmall(!small)} className="absolute -right-3 top-24 hidden size-7 place-items-center rounded-full border bg-white text-slate-500 shadow lg:grid">{small?<ChevronRight size={15}/>:<ChevronLeft size={15}/>}</button></aside>{mobile&&<button aria-label="Fechar menu" className="fixed inset-0 z-30 bg-slate-900/30 lg:hidden" onClick={()=>setMobile(false)}/>}<div className={small?'lg:pl-20':'lg:pl-64'}><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur md:px-7"><button className="grid size-11 place-items-center rounded-xl border lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="hidden lg:block"><p className="text-sm text-slate-500">Bem-vindo de volta,</p><p className="font-semibold">{profile?.full_name||'Usuário'}</p></div><AppointmentNotifier/><div className="grid size-10 place-items-center rounded-full bg-violet-100 font-semibold text-violet-700">{profile?.full_name?.charAt(0)||'U'}</div></header><main className="p-4 pb-24 md:p-7 lg:pb-7"><Outlet/></main></div><nav className="safe-bottom fixed inset-x-0 bottom-0 z-20 grid grid-cols-4 border-t bg-white px-2 pt-2 lg:hidden">{items.slice(0,4).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>`flex flex-col items-center gap-1 text-[11px] ${isActive?'text-violet-700':'text-slate-500'}`}><Icon size={21}/>{label}</NavLink>)}</nav></div>}











